### ISSUE TITLE
'EasyRdf_Exception' with message 'Failed to parse HTTP response status line.'

### ISSUE THREAD

**Issue by robertbbb** [easyrdf/easyrdf#278]
Hi,

I get this exception when using EasyRDF_Sparql_Client on the SPARQL endpoint provided by RDF4J (formerly known as OpenRDF Sesame), which works on top of Tomcat.

What I was able to figure out is that the error occurs only for recent versions of Tomcat (there's no error on Tomcat 8.0, but there starting from Tomcat 8.5.x).

Maybe the error is in the regular expression from easyrdf/lib/EasyRdf/Http/Response.php
if (preg_match("|^HTTP/([\d\.x]+) (\d+) ([^\r\n]+)|", $status, $m)) 

Something might have changed in this status for recent versions of Tomcat?

**Comment by njh** [comment]
Hello,

That is odd.

Are you able to make a request via ```curl -v``` and send paste the output into this issue?

nick.

**Comment by Knurg** [comment]
For anybody who also has this issue: it is due to tomcat 8.5.x, see https://github.com/spring-projects/spring-boot/issues/6548

Tomcat skips the "reason phrase" from there on, so the header for the typical request is no more
HTTP/1.1 200 OK
but 
HTTP/1.1 200

As this seems to be legal the preg_match("|^HTTP/([\d\.x]+) (\d+) ([^\r\n]+)|", $status, $m) should be changed to preg_match("|^HTTP/([\d\.x]+) (\d+) ([^\r\n]*)|", $status, $m) or something like that.

Best
Knurg

**Comment by adam-clarey** [comment]
I'm having this same issue when connecting to GraphDB via Rest API.

preg_match("|^HTTP/([\d.x]+) (\d+) ([^\r\n]*)|", $status, $m) fixes this issue

**Comment by tkw1536** [comment]
This has have been fixed in https://github.com/easyrdf/easyrdf/commit/231bb1af8668bc29b0a8e1ea262aba725be4c0ae. It's just that no one appears to have bothered to update or close this issue.
