### ISSUE TITLE
Website easyrdf.org should be removed

### ISSUE THREAD

**Issue by k00ni** [easyrdf/easyrdf#342]
The website easyrdf.org shoud be **removed** and all attention should be directed to this repository. Website is widely outdated and therefore not reliable. It seems the effort required to bring it back were it was seems not worth it.

We could move most doc-content to this repository and keep it up to date. That would allow others to help too.

**Comment by njh** [comment]
In your opinion?

**Comment by akuckartz** [comment]
Maybe better redirect easyrdf.org here instead of removing it?

**Comment by njh** [comment]
Hi Konrad, 

I understand that you are very frustrated but please consider how sending messages like this may come across. I have been working very hard on trying to get EasyRdf fixed up, in the little time that I have between work and home life and receiving a message like this was not very encouraging.

Not everyone is like you and has same set of skills that you have; Github, developing code and using a package manager.

The [easyrdf.org](http://easyrdf.org/) website does have a steady stream of visitors and has the following benefits:
- A welcoming entry point that makes the purpose of EasyRdf clear, without being cluttered with what an experienced developer might be looking for
- A converter that makes it quick for people to start playing with RDF and test out EasyRdf
- A Googlable documentation and API Reference 

Just because you don't see any value in it, does not mean that there is no value.

If there are things that are obviously out of date, or need fixing, I would applicate the help to improve it:
https://github.com/easyrdf/www.easyrdf.org

The latest version is currently deployed here:
https://new.easyrdf.org/


nick.

**Comment by akuckartz** [comment]
I agree with closing this issue and just noted that not a single issue was reported regarding the content of easyrdf.org: https://github.com/easyrdf/www.easyrdf.org/issues

**Comment by k00ni** [comment]
Hi, thank you for the feedback. My intention with this issue was not discourage anyone, but to ask for changes that might benefit EasyRdf as a whole (focus our spare time more). If you disagree, that's fine, no hard feelings.
