### ISSUE TITLE
Call for collaborators!

### ISSUE THREAD

**Issue by njh** [easyrdf/easyrdf#345]
Hi,

Now that I have got version 1.0.0 out of the door, it would be really good to get some help with the future of EasyRdf. As I said in #320, I no-longer do PHP or RDF for my day job and have lots of other projects that I am interested in. So I would really like some help with maintaining EasyRdf and ensure that it has a good future.

Some of the tasks I would really like people to collaborate on:

- Help direct the future of the project
- Review issues and tag them
- Review Pull Requests
- Respond to questions on the [mailing list](https://groups.google.com/group/easyrdf) and [Stack Overflow](https://stackoverflow.com/questions/tagged/easyrdf)
- Fix bugs!
- Writing [documentation](https://github.com/easyrdf/easyrdf/tree/master/docs)
- Enforce the [Code of Conduct](https://github.com/easyrdf/easyrdf/blob/master/CODE_OF_CONDUCT.md)
- Updating the [website](https://github.com/easyrdf/www.easyrdf.org)
- Anything else that you think help people make the most of EasyRdf

The plan is that nobody (including myself) will be able to commit directly to the master branch and that everyone will submit changes for review via Pull Requests. Depending on how many people are actively involved in EasyRdf, GitHub will require at least one review of the Pull Request before it can be merged.

So if you would like to be added as a collaborator to the EasyRdf organisation, please comment below. Ideally you would have already contributed to EasyRdf and other open source projects.

Feedback very welcome...

Thanks!

nick.

**Comment by njh** [comment]
Overnight I realised that all this list might seem really daunting.

If nothing else, what would be really good is to have multiple people reviewing Pull Requests...

**Comment by k00ni** [comment]
I can help with code reviews, project organization, issues, tag things and maybe a bug fix.

As far as I am concerned Github is the place to be for now. I am already here because of other projects and it is easier to follow up on things. It is great that people are still willing to contribute, but I am afraid there are some obstacles we have to remove next to make contribution easier. Obstacles like test environment fixes (https://github.com/sweetyrdf/easyrdf/pull/19), easier tooling and better integration of tools like Scrutinizer. Some is already done in my fork. Therefore some feedback on my pull requests would be highly appreciated.

**Comment by njh** [comment]
Thanks @k00ni.

Yup, hope to find time soon to review those open PRs and then add you as a contributor.

**Comment by k00ni** [comment]
What do we do, if @njh and I are the only ones maintaining this library (and approve PRs)?

I observe the whole situation since May (after starting my fork). Since then there were a handful contributions by 2 people. But there was no further feedback on foreign code. It is what it is, that's fine. Just asking to form a perspective.

**Comment by njh** [comment]
I thought we might get one other person to review PRs. Oh well.

For the time being:
- @k00ni reviews/approves PRs by @njh 
- @njh reviews/approves PRs by @k00ni 
- We both review PRs by others

I have added you (@k00ni) as a collaborator with **Write** role.
Sorry, I still I need to find time to review the open PRs.

**Comment by k00ni** [comment]
@njh thank you for reviewing my PRs. While reading your feedback and the comments of @zozlak, I was thinking. For me, we have a situation in which EasyRdf came back to live and gets started to be maintained. And there are forks which contain fixes and changes, which might be also beneficial for EasyRdf as well (take contributions from @zozlak for instance).

There is debt from the past (e.g. bugs, documentation problems, ...) which needs to be handled in some way. But also new contributions. So we should decide on our preferences to shape development.

I suggest we the following as a way to concern time limitations as well as include foreign contributions:

* create a **1.x** branch which only receives fixes and new features (alternatively keep the master branch for that)
* create a **2.x** branch which receives breaking changes (like #338?)
  * changes in 1.x will be merged in 2.x regularly

This way we can have it "both ways": keep 1.x stable as well as allow breaking changes/new features.

What do you think?

**Comment by k00ni** [comment]
I would like to suggest that @zozlak and @osma receive collaborator rights too, if they want. We need help with the PRs, desperately. Both proofed to have good knowledge about RDF and EasyRdf. But I don't want to push you guys.

@njh I know that you are busy, but can you give me a raw timeline on the PRs? We are in a situation with some PRs outdated, some ready to merge (require a re-review) and the rest in between.

Further hands would help, otherwise I am afraid EasyRdf runs in the same "stale" state it was before my fork and #320.

**Comment by njh** [comment]
The call for collaborators is still open. @zozlak and @osma would be very welcome.

I have just gone through all the PRs @k00ni raised and approved/merged the ones that don't require further work.

Down to 10 Open PRs now!

Would be really good to get the ones related to large XML files sorted out.
I think we need a new PR that just fixes large XML outside of the RDF/XML parser.

**Comment by zozlak** [comment]
I am definitely glad to contribute but I can not guarantee my time availability (e.g. I expect I wont' have much time for the EasyRdf until the end of October).

**Comment by njh** [comment]
Thats great, thanks @zozlak 👍
No need to guarantee time; helping when you can would be great.

**Comment by k00ni** [comment]
Github extended its sponsoring program to organizations. EasyRdf is still directly or indirectly used by many libraries and maybe in commercial projects too.

I propose we add a sponsor button and use that money for bounties on (important) feature requests or changes. There could be other platforms which do that better or provide more functions, I didn't check. Feedback and ideas welcomed.

**Comment by k00ni** [comment]
Since my initiative #320 and the changes we made since, I hoped for a more fluid and consistent development of EasyRdf. We finished a lot open issues and PRs in comparison to the years before, but after a few months there was it again: stagnation.

@njh you said it multiple times: you are not using RDF that often anymore and I can imagine that your spare time is limited. That is totally understandable and fine. 

But it collides with the current setup of this repository, because pull requests need to be accepted by one of the collaborators. As far as I know, that is you and me. A good example is #373 which is open since 1 Dec 2020 and got reviewed. But we can't merge it, because we need your review.

I am a little bit frustrated, but I don't want you leave this repository out in the cold, therefore my last attempt: **Please change the PR policy so that a merge can be made by any collaborator, if they see it**. This way I can merge my own PRs if you or others don't have time to review. As I do it with all my projects, I listen to peoples opinion and invite foreign reviews. That wont change.

If I hear no feedback until end of this week I move along. Don't wanna waste my time here if its all stuck again.

**Comment by njh** [comment]
My understanding is that:
* If @njh raises a PR, either @k00ni or @zozlak has to review it
* If @k00ni raises a PR, either @zozlak or @njh has to review it
* If @zozlak raises a PR, either @k00ni or @njh has to review it
* If some other person raised a PR, any of @zozlak or @k00ni or @njh has to review and merge it

Is it behaving differently to my understanding? If so, I can try changing the settings.

I had hoped that more people would volunteer to review PRs.
But I think the review process has picked up a few things, so isn't worthless.
I do think it is more worthwhile being careful with a _mature_ project than it is with an amazing brand new thing that nobody is using (yet).

**Comment by k00ni** [comment]
Thank you for your replies (also in my PR). 

> Is it behaving differently to my understanding? If so, I can try changing the settings.
> I had hoped that more people would volunteer to review PRs.
> But I think the review process has picked up a few things, so isn't worthless.
> I do think it is more worthwhile being careful with a mature project than it is with an amazing brand new thing that nobody is using (yet).

I didn't say that reviews are worthless, that is the opposite of what I wrote:
> As I do it with all my projects, I listen to peoples opinion and invite foreign reviews. That wont change.

The problem is that the only people who made contributions in the last couple of months were you and me (besides #355 and #369). While I reviewed your PRs after a few days max, my PRs were unanswered for weeks or longer and I have to ping you to get feedback (or my code merged). I value @zozlak feedback, but he stated that he can't be that invested here for various reasons. So we can't count on him doing reviews.

My impression is that you don't want your baby given into foreign hands. It might be one of the reasons. That is fine by me, but in that case I can't help out here anymore. 

To act as a real maintainer I need more rights to actually maintain. For instance, why can't I change settings or create new repositories? Also, I can't be depended on your time schedule.

**Comment by zozlak** [comment]
I support @k00ni here. It's clear for me that you (@njh) don't have enough time to actively support EasyRdf. I don't have it too by the way. Anyway it leaves us only with @k00ni being able to do the job and to do it smoothly he needs permissions. Lack of them causes his frustration which I perfectly understand.

On the other hand I understand you're being afraid of loosing control of your project. It can be considered pretty feature-complete and stable as it did the job for users despite no development took place for quite a few years. Despite it's limitations it's probably still the best choice for general purpose RDF processing in PHP. But I have two concerns here:

* Is there a real risk of loosing this by more aggressive development? Personally I would say not really and we always have semantic versioning to draw a clear line between what's only maintaining a stable product and adding new (and possibly not-so-stable) features.
* What's more important - keeping control over your project and risking bigger fragmentation of the RDF PHP community or letting it go and trying to gather the community around EasyRdf. As this is a very personal one and I'm clearly biased, I won't tell my opinion here :-)

Anyway at the end of day it's really simple:

* We made an experiment. The results are that at the moment the only person which has time and enthusiasm is @k00ni.
* To make proper use of his time and enthusiasm @k00ni needs admin rights.
* This can go either by elevating his rights within the EasyRdf or by forking.
* Decision to elevate @k00ni  rights is up to @njh . Lack of action will (sooner or later) cause a fork.

**Comment by njh** [comment]
I agree that the experiment is not working.  Nobody is paid to work on EasyRdf, as such the main motivations for working on it is learning, the satisfaction of helping other people and fun. But this has stopped being fun, it is causing me anxiety and it is clearly not making either you happy either.

@k00ni has injected enthusiasm, time and effort into the project, for which I am grateful for. I am particularly delighted that version 1.0.0 finally got released after many years and that it works with modern PHP versions. And it is fantastic that backlog of PRs got cleared down.

I would love to see EasyRdf continue to be used and evolved and be handed over to a maintainer who has the skills and enthusiasm to continue with it. However, I don't think @k00ni is the right person for the job. Perhaps is it just a difference of opinion on what is important for the project. Perhaps if @k00ni is motivated to create a fork, I will see that I was wrong.

But I think, for now, I will just continue to keep things as they are, slowly fix bugs and merge PRs when I have the time. Hopefully not feeling guilty and pressured will make it fun again. And maybe someone else will come along in the future and want to have a go at helping maintain EasyRdf.

**Comment by k00ni** [comment]
I thought long about how to react to a comment like this, but decided that its better to move along. People will decide for themselves by reading my posts and check my contributions. 

For what its worth, I will maintain EasyRdf in my fork at https://github.com/sweetrdf/easyrdf and welcome anyone to use it and give feedback.

**Comment by njh** [comment]
@k00ni I wish the the best of luck with your fork.

But please can you rename it from EasyRdf to something else?
I don't want people to be confused that your fork is the future of EasyRdf - it is something new and different.
