### ISSUE TITLE
Use hardf library to parse turtle, n-triples, n-quads, TriG and N3

### ISSUE THREAD

**Issue by k00ni** [easyrdf/easyrdf#353]
### About hardf

https://github.com/pietercolpaert/hardf developed by @pietercolpaert

*For transparency: I help out with maintenance from time to time.*

hardf claims to be much faster on parsing in comparison with EasyRdf or ARC2.

| #triples | framework               | time (ms) | memory (MB) |
|----------:|-------------------------|------:|--------:|
|1,866    | __Hardf__ without opcache |  27.6   |   0.722     |
|1,866    | __Hardf__ with opcache    |   24.5   |    0.380    |
|1,866    | [EasyRDF](https://github.com/njh/easyrdf) without opcache |   5,166.5   |    2.772   |
|1,866    | [EasyRDF](https://github.com/njh/easyrdf) with opcache    |  5,176.2    |  2.421     |
|1,866    | [ARC2](https://github.com/semsol/arc2) with opcache | 71.9 | 1.966 |
| 1,866  |   [N3.js](https://github.com/RubenVerborgh/N3.js) |  24.0    |  28.xxx  |
| 3,896,560  |   __Hardf__ without opcache |  40,017.7    |  0.722   |
| 3,896,560  |   __Hardf__ with opcache |    33,155.3  |    0.380   |
| 3,896,560  |   [N3.js](https://github.com/RubenVerborgh/N3.js) |  7,004.0    |  59.xxx    |
| 3,896,560  |  [ARC2](https://github.com/semsol/arc2) with opcache | 203,152.6 | 3,570.808  |

Table source: https://github.com/pietercolpaert/hardf#performance

### My suggestion

I would like to use hardf to replace EasyRdf code for parsing and serializing turtle, n-triples, n-quads, TriG and N3. Our API should be kept, but the code behind it could be (massively) reduced and replace by hardf pendants.

**Advantages:**
* We won't have to care about related parser / serializer issues anymore - **more free time** and less code to maintain
* It's a faster and more memory-sufficient parsing solution (its seems to be based on knowledge from N3.js)

Sure, hardf code may need some attention (e.g. coding styles) and there is currently a bug, which lead to some tests fail on PHP 7.4 (https://github.com/pietercolpaert/hardf/pull/28). But its nothing we couldn't handle.

What do you think?

CC @njh, @osma, @zozlak, @pietercolpaert

**Comment by osma** [comment]
Sounds good in principle - better performance, less maintenance. But no idea how difficult this would be in practice.

If implementation goes ahead it would make sense to break this up into smaller pieces - perhaps switching over parsers and serializers independently, and also doing one syntax at a time.

**Comment by zozlak** [comment]
I like the idea. It's quite a major work but I think it might be worth it.

I would couple this change with a general parser infrastructure revamp which would allow to use streams. At the moment the common parser infrastructure causes the whole input to be read into the memory so I'm afraid we won't achieve any memory usage gains with the hardf.

**Comment by zozlak** [comment]
Fun fact - I've checked hardf, easyrdf and my own easyrdf fork on at 65MB ttl (960k triples) and the results are as follows:

* easyrdf 1.0.0 - 200 s, memory usage 5.3 GB
* acdh-oeaw/easyrdf 0.14.1 - 204 s, memory usage 5.3 GB
* hardf 0.1.3 alone - 652 s, memory usage 0.5 GB
* hardf 0.1.3 with (oversimplified) calls to `EasyRdf\Graph::add()` - 732 s, memory usage 1.2 GB
* easyrdf 0.9.1 - killed after few hours of waiting; it's a hopeless case - in easyrdf <= 0.9.1 turtle parsing time in relation to data size grows faster than linear

The bottleneck in easyrdf's <=0.9.1 turtle parser was constant string copying.
It has been solved in two different ways in easyrdf 1.0.0 and acdh-oeaw/easyrdf (personally I consider easyrdf's 1.0.0 solution more elegant) and it looks like the current implementations outperform hardf significantly.

Where hardf clearly wins is the memory footprint because it can deal with data being provided in chunks. But this benefit can be achieved only while running hardf "on top of easyrdf" and implementing it as another easyrdf parser class would take away this benefit (yes, I should take some time and propose an easyrdf code revamp here which would allow to pass streams to parsers).

**Comment by k00ni** [comment]
So we can decide between memory-exhaustion or factor 3+ on time consumption. That's unexpected, thank you for testing it! 

Maybe @pietercolpaert can tell us a bit about his performance suite.

**Comment by njh** [comment]
Very interesting and surprising working @zozlak!

Guess it was 7624bb90f2dc53bb2083c2ae397345825fb0d165 that sped things up.
I had always assumed that rather than parsing byte-by-byte in PHP, it would be faster to use regular expressions in some way.

I guess it might be possible to optimise memory usage - but ultimately the whole design of EasyRdf is to load all the triples into memory, so that the graph can be walked and explored. It does create two indexes of the triples (one reverse) - maybe there is a way of optimising that.

I did consider changing the parsing/serialising classes to stream the input/output and then use callback functions to handle adding triples - but that felt like it almost should be a different library (eg ARC2) - see #122 and #123.

**Comment by pietercolpaert** [comment]
> **EDIT:** But how can it be that hardf parses 3,896,560 triples within 40 sec?!

You mean you cannot reproduce these results? Because I just tested the last version of hardf again on a big file and I seem to be able to still get decent performance:
```
* Time spent: 31.976636886597s
* Triples parsed: 5125811
* Memory usage: 0.90869140625MB
```
And another file:
```
* Time spent: 40.485129117966s
* Triples parsed: 6370760
* Memory usage: 0.91267395019531MB
```

The code for testing the performance can be found here: https://github.com/pietercolpaert/hardf/blob/master/perf/parser-streaming-perf.php

@zozlak Is your slow performance results of hardf a result of then trying to load the graph into EasyRDF?

**Comment by osma** [comment]
7624bb9 was the work of my (now ex-)colleague Henri. We diagnosed the problem together (basically, the `mb_*` functions in PHP are horribly slow especially for long strings, as they always start the decoding from the beginning of the string...) and designed the fix, then he implemented it. There's some more background in PR #295.

**Comment by zozlak** [comment]
> @zozlak Is your slow performance results of hardf a result of then trying to load the graph into EasyRDF?

@pietercolpaert as I described - the hardf-only code (just adding each triple at the end of a PHP array, so the memory footprint includes storing parsed results in RAM) took 652 s while adding `EasyRdf\Graph::add()` calls added another 80 s on top of it.

Anyway I would expect time (and memory) spend on parsing (and storing parsed data) depends a lot on the actual triples being parsed (especially "object" parts size), so it's not enough to link to the test code but we must also provide our test RDF files.
Alternatively we should try to parse the same data with different libraries.

**Comment by k00ni** [comment]
> Anyway I would expect time (and memory) spend on parsing (and storing parsed data) depends a lot on the actual triples being parsed (especially "object" parts size), so it's not enough to link to the test code but we must also provide our test RDF files.
Alternatively we should try to parse the same data with different libraries.

Any real life example which might be worth parsing?

**Comment by osma** [comment]
> Any real life example which might be worth parsing?

I'm taking this as an opportunity to be blatantly selfish and so I suggest this [Skosmos configuration file](https://github.com/NatLibFi/Finto-data/blob/master/conf/dev.finto.fi/config.ttl). This is parsed by Skosmos on every page load (except it's cached with APCu if enabled) so it's performance critical for us. It's about 1.5k triples of Turtle. Note that this file in GitHub is changing quite frequently, so it might make sense to use an archived copy. I can provide a sanitized one if necessary (the current one contains some e-mail addresses).

**Comment by k00ni** [comment]
Any feedback on your performance tests @zozlak and @pietercolpaert?

**Comment by pietercolpaert** [comment]
In order to have a comparison that makes everyone smarter there should be an agreed interface and test case we try to implement with different back-ends. Can you do a proposal in a new repo?

**Comment by k00ni** [comment]
That should this repository contain/provide?

**Comment by zozlak** [comment]
This repository will provide a framework (basically an interface and its implementations for various backends) for performance testing, sample data and a CD workflow which will run the tests automatically. I will prepare it no later than last week of December.

**Comment by zozlak** [comment]
@k00ni who has permissions to create a repository in the easyrdf ogranization? (cause I don't)

**Comment by k00ni** [comment]
Me neither. 

CC @njh

**Comment by zozlak** [comment]
Please take a look at the https://github.com/zozlak/easyRdfParserPerf

**Comment by zozlak** [comment]
So we have some [results](https://github.com/zozlak/easyRdfParserPerf/suites/1754653060/artifacts/33386990) (as this is a link to a gihub actions job artifact accessing it may require some rights on the repository and you definitely have to be logged into the github) for few datasets ranging from 1.5k to 100k triples in ttl, ntriples and xml formats and it looks like:

* If you really value performance, store your RDF as ntriples and use a dedicated (read *simplified*) ntriples parser. This scenario favors EasyRdf as it looks like the n3 doesn't have a simplified (and therefore faster) version of the parser for ntriples (or at least I don't know how to set it up to use it).
* Surprisingly the second fastest solution is to use RDF-XML with EasyRdf (n3 doesn't have an RDF-XML parser).
* Finally if you really must use turtle, than Hardf **in chunked mode** is the most performant choice being around 4x faster than EasyRdf.

**Comment by k00ni** [comment]
What do you think @pietercolpaert?

**Comment by pietercolpaert** [comment]
I’m surprised hardf without chunked mode is so slow. I should investigate that, but overcommitted with other projects at this moment.

**Comment by zozlak** [comment]
I'm too lazy to look into the code but my guess is it's simply because of too much memory being copied in the non-chunked mode on large data (and my tests include quite big one). Regexps can be fast but if there is a string subsetting after each mach and it's done on a large string, performance will suffer.

By the way if data are small, it's not important and if data are big, I would use chunked mode anyway.

**Comment by pietercolpaert** [comment]
Interesting! Maybe we should then always default to the chunked mode

**Comment by zozlak** [comment]
Sounds reasonable. Just it would be good to provide a wrapper for easier use (taking a resource as a parameter and performing read in chunks internally).

I have a piece of code doing that and also turning the `TrigParser` into a lazy triples/quads `Generator`. I should prepare a PR I think... (rather in the hardf repo of course).

**Comment by zozlak** [comment]
Dear @claudiu-cristea only @njh has merge rights in this repo and he's inactive for around two years. As for now this repository is effectively abandoned. I can see you already gave a try to the @k00ni fork and you should probably just stick to it.
