### ISSUE TITLE
RDF*

### ISSUE THREAD

**Issue by robertbbb** [easyrdf/easyrdf#362]
RDF* was adopted by most major RDF vendors during 2019-2020, facilitating the processing of reifications such as

<<:George :workedAt :IBM>> :during 2020 .

It would be nice if the feature would find its way in RDF libraries as well.

**Comment by njh** [comment]
@robertbbb do you have any suggestions about what this might look like in PHP / EasyRdf?

**Comment by zozlak** [comment]
I can imagine three sets of RDF\* related features:

* RDF\* parsers
* RDF\* serializers 
* New API methods allowing to interact with RDF\* statements in a convenient way (e.g. get a set of triples being metadata of a given triple)

First two seem doable without any major changes. All in all RDF\* can be expressed as a standard RDF graph (as described in https://arxiv.org/pdf/1406.3399.pdf chapter 3.2) so it can be parsed into current EasyRdf data structures.

The last one seems hard. The main problem is the EasyRdf doesn't recognize a triple as a first-class API object so we lack an RDF\* statement equivalent. It means to introduce an RDF\* friendly API we would either need to completely restructure the current API or to create a completely parallel API. Both options seem bad to me.

**Comment by zozlak** [comment]
But even for parsers and serialisers the question is who would have time and interest to implement them. I'm afraid I won't.

**Comment by njh** [comment]
I agree with @zozlak. I can't quite see how this could be implemented in EasyRdf.

If anyone has an idea, please comment but in the meantime I think we should close this as "Won't fix".

**Comment by akuckartz** [comment]
This issue is the main reason why I am watching this repository.

**Comment by k00ni** [comment]
I follow @njh and @zozlak on this.

This feature seems quite helpful but as it seems that no one will implement it in the near future. If someone wants to work on this, please comment here or open a new PR. I will help if I can.

**Comment by akuckartz** [comment]
Please mention me in case there are new developments regarding this issue as I have reduced the watch level.

**Comment by zozlak** [comment]
@akuckartz To be honest I think it will be closed forever as:

* Implementing RDF* in a nice way would require the whole easyrdf to be rewritten from the ground because it doesn't recognize a triple as a first class citizen in its API and the whole RDF* is about that.
* I guess no one interested in this feature will be happy with just parsing RDF* into normal RDF as it takes away most of the benefits of RDF*, most importantly the easiness of accessing/defining triples describing other triples. But really guys, please make an effort, go trough chapter 3.2 of https://arxiv.org/pdf/1406.3399.pdf and let us know if it would do the job for you or not.
* None of easyrdf maintainers needs it and you know how the free software works...

**Comment by zozlak** [comment]
@akuckartz you can take a look at the [quickRdfIo](https://github.com/sweetrdf/quickRdfIo). It provides an n-triples-star parser and serializer. Remarks:
* You can't couple it with EasyRdf but there is [quickRdf](https://github.com/sweetrdf/quickRdf) which provides `EasyRdf\Graph` equivalent (`quickRdf\Dataset`), just with slightly different API (graph edges oriented while EasyRdf has graph nodes oriented one).
* There is no support planned for turtle-star parsing/serialization (at least until [hardf](https://github.com/pietercolpaert/hardf) is made in line with [N3.js](https://github.com/rdfjs/N3.js) developments). It's just too complex and not needed for machine2machine communication, therefore out of scope of my interest.
* `\quickRdfIo\NQuadsParser` passes [n-triples](https://w3c.github.io/rdf-tests/ntriples/), [n-quads](https://w3c.github.io/rdf-tests/nquads/) and [n-triples-star](https://w3c.github.io/rdf-star/tests/nt/syntax/manifest.html) test suites but it doesn't guarantee there are no errors in the implementation (especially the "positive" tests in those suites check only for no error during the parsing and not for parsing results matching the expected value; what makes it a little better is that quickRdfIo\NQuadsParser` has a few modes and there is cross-validation performed between their results).
* `quickRdf\Dataset` API is not considered stable yet. I'm still experimenting a lot with how to achieve the API flexibility and orthogonality.
* I can't guarantee any schedule for quickRdfIo and quickRdf development. It's a hobby project.

Also a short explanation for @njh. As you can see I started experimenting with a completely separate library (or precisely ecosystem of libraries). I decided to take this approach instead of contributing to the EasyRdf as first, most features I wanted to play with can't be implemented in EasyRdf without severly affecting both it's API and internals and second, I fully understand your preference to keep EasyRdf's API stable. I don't see quickRdf as a competition to EasyRdf and I don't plan to advertise it broadly but if you have nothing against, I may sometimes point people to it if a feature they are looking for has no real chances of being implemented in the EasyRdf and can be provided by the quickRdf ecosystem (like support for the RDF star).
