### ISSUE TITLE
Converting return to json

### ISSUE THREAD

**Issue by ianpiper** [easyrdf/easyrdf#371]
I'm using EasyRDF to manage a SPARQL query to a remote data service. It works fine when I use a simple search box; I get a $return object and I can retrieve the separate results from that. However, I'd like to make the search box autocomplete and get the results in a dropdown as I type. The various resources I've read suggest that I need to build a piece of json and use that to populate the autocomplete list. However, I can't see how to make a json object out of the return from my program.

I've tried json_encode but that doesn't seem to work. Can anyone advise please? Any help much appreciated.

For information, here is the raw dump data that I get back from a typical search. This is just the first section and then the first array member. Apologies for any mangled formatting.

```
object(EasyRdf\Sparql\Result)#20 (4) {
  ["type":"EasyRdf\Sparql\Result":private]=>
  string(8) "bindings"
  ["boolean":"EasyRdf\Sparql\Result":private]=>
  NULL
  ["fields":"EasyRdf\Sparql\Result":private]=>
  array(2) {
    [0]=>
    string(7) "concept"
    [1]=>
    string(11) "searchLabel"
  }
  ["storage":"ArrayIterator":private]=>
  array(5) {
    [0]=>
    object(stdClass)#33 (2) {
      ["concept"]=>
      object(EasyRdf\Resource)#38 (2) {
        ["uri":protected]=>
        string(89) "https://mysite.com/mygraph/63239bad-80e8-4510-9864-c89217164c73"
        ["graph":protected]=>
        NULL
      }
      ["searchLabel"]=>
      object(EasyRdf\Literal)#40 (3) {
        ["value":protected]=>
        string(25) "Stomata and gas diffusion"
        ["lang":protected]=>
        string(2) "en"
        ["datatype":protected]=>
        NULL
      }
    }
```

**Comment by njh** [comment]
I have just tried adding the following to the `basic_sparql.php` example:
```
echo json_encode($result);
```

```
And then also:
$array = iterator_to_array($result);
echo json_encode($array);
```

Both output:
```json
[{"country":{},"label":{}},{"country":{},"label":{}},{"country":{},"label":{}},{"country":{},"label":{}},{"country":{},"label":{}},{"country":{},"label":{}},{"country":{},"label":{}},{"country":{},"label":{}},{"country":{},"label":{}},{"country":{},"label":{}},{"country":{},"label":{}}....
```

I think this is because `json_encode` doesn't know how to convert `EasyRdf\Resource` and `EasyRdf\Literal` into JSON.

We might be able to improve this by making them implement [JsonSerializable](https://www.php.net/manual/en/class.jsonserializable.php).
But different people might want different JSON and expose different amounts of the SPARQL result. Not sure.

I think you might need to convert the results object into a plain array yourself.

This works for me in the in the basic_sparql.php example:
```php
    $result = $sparql->query(...);

    $mapping = array();
    foreach ($result as $row) {
        $mapping[strval($row->country)] = strval($row->label);
    }
    echo json_encode($mapping);
```

Alternatively maybe what we be useful is a method of turning a `EasyRdf\Sparql\Result` object back into JSON or XML.
But then maybe you are better not parsing the SPARQL response at all.

**Comment by njh** [comment]
Not had feedback about wether my response was helpful or not. Closing.
